language: php
sudo: false

php:
  - 7.0
  - 7.1

os:
- linux

matrix:
  include:
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" COVERAGE=true TEST_COMMAND="composer test-ci"

script:
  - $TEST_COMMAND